auto_save: false
auto_open_next_eval: true
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_annotation_color: [0, 255, 0]
annotation_color: auto  # null, 'auto', 'manual'
shift_auto_annotation_color: 0
label_colors: null

tiff_real_bitdepth: 11

# geo-json configuration
geo:
  label: "cropsid"
  id: null
  shape_type: "type"

annotation:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]

# main
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
annotator_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+K, Ctrl+O
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [Right, Ctrl+Shift+N]
  open_prev: [Left, Ctrl+Shift+P]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  move_annotation: Ctrl+M
  delete_annotation: Delete
  duplicate_annotation: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+Shift+A
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+K
