auto_save: false
auto_open_next_eval: true
display_label_popup: true
store_data: true
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

theme:
  default: "bluesky"
  "bluesky":
    "QMainWindow, QToolBar{color:rgb(0,64,128); background-color:rgb(220,238,248); border:1px solid white; selection-color: blue;}"
    

default_annotation_color: [0, 255, 0]
annotation_color: manual  # null, 'auto', 'manual'
shift_auto_annotation_color: 0
labels: {
  "비대상지": {
    "code": 0,
    "gray": 100,
    "color": [100,100,100]
  },
  "건물": {
    "code": 10,
    "gray": 10,
    "color": [157,47,34],
  },
  "주차장": {
    "code": 20,
    "gray": 20,
    "color": [144,88,175],
  },
  "도로": {
    "code": 30,
    "gray": 30,
    "color": [168,53,112],
  },
  "가로수": {
    "code": 40,
    "gray": 40,
    "color": [177,200,122],
  },
  "논": {
    "code": 50,
    "gray": 50,
    "color": [179,126,82],
  },
  "밭": {
    "code": 60,
    "gray": 60,
    "color": [199,182,152]
  },
  "산림": {
    "code": 70,
    "gray": 70,
    "color": [30,99,34]
  },
  "나지": {
    "code": 80,
    "gray": 80,
    "color": [42,105,140]
  },
}


tiff_real_bitdepth: 11

# geo-json configuration
geo:
  default_others: {
    "type": "FeatureCollection",
    "name": "Zone-A-001",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32652" } },
  }
  label: "cropsid"
  id: null
  shape_type: "type"

annotation:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0]  # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]

# main
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
annotator_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+K, Ctrl+O
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [Right, Ctrl+Shift+N]
  open_prev: [Left, Ctrl+Shift+P]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  move_annotation: Ctrl+M
  delete_annotation: Delete
  duplicate_annotation: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+Shift+A
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+K
